services:
    kavita:
        image: jvmilazz0/kavita:0.8.1    # Using the stable branch from the offical repo.
        container_name: kavita
        volumes:
            - library:/library
            - config:/kavita/config     # Change './data if you want to have the config files in a different place.
                                        # /kavita/config must not be changed
        environment:
            - TZ=Europe/Berlin
        ports:
            - "5000:5000" # Change the public port (the first 5000) if you have conflicts with other services
        restart: unless-stopped
volumes:
  library:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=${SHAREIP},rw"
      device: ":${SHAREFOLDER}/kavita_library"
  config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=${SHAREIP},rw"
      device: ":${SHAREFOLDER}/kavita_config"
      