version: '3'
services:
  orbital-sync:
    image: mattwebbio/orbital-sync:latest
    environment:
      PRIMARY_HOST_BASE_URL: ${PRIMARY_HOST_BASE_URL}
      PRIMARY_HOST_PASSWORD: ${PRIMARY_HOST_PASSWORD}
      SECONDARY_HOSTS_1_BASE_URL: ${SECONDARY_HOSTS_1_BASE_URL}
      SECONDARY_HOSTS_1_PASSWORD: ${SECONDARY_HOSTS_1_PASSWORD}
      INTERVAL_MINUTES: 60