version: '3.5'

services:
    cobalt-api:
        image: ghcr.io/wukko/cobalt:7
        restart: unless-stopped
        container_name: cobalt-api

        init: true

        # if container doesn't run detached on your machine, uncomment the next line
        #tty: true

        ports:
            # - 16515:9000/tcp
            # if you're using a reverse proxy, uncomment the next line and remove the one above (9000:9000/tcp):
            - 7652:9000

        environment:
            # replace https://co.wuk.sh/ with your instance's target url in same format
            API_URL: "${API_URL}"
            # replace eu-nl with your instance's distinctive name
            API_NAME: "${API_NAME}"
            # see docs/run-an-instance.md for more information
        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

        # if you want to use cookies when fetching data from services, uncomment volumes and next line
        #volumes:
            #- ./cookies.json:/cookies.json

    cobalt-web:
        image: ghcr.io/wukko/cobalt:7
        restart: unless-stopped
        container_name: cobalt-web

        init: true

        # if container doesn't run detached on your machine, uncomment the next line
        #tty: true

        ports:
            # if you're using a reverse proxy, uncomment the next line and remove the one above (9001:9001/tcp):
            - 5416:9001

        environment:
            # replace https://cobalt.tools/ with your instance's target url in same format
            WEB_URL: "${WEB_URL}"
            # replace https://co.wuk.sh/ with preferred api instance url
            API_URL: "${API_URL}"

        labels:
            - com.centurylinklabs.watchtower.scope=cobalt