version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:0.26.1
    ports:
      - '8080:8080'
    volumes:
      - training:/usr/share/tessdata #Required for extra OCR languages
      - configs:/configs
#      - /location/of/customFiles:/customFiles/
#      - /location/of/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
volumes:
  training:
  configs: