version: '3'
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:24.6.0
    ports:
      # This line makes Actual available at port 5006 of the device you run the server on,
      # i.e. http://localhost:5006. You can change the first number to change the port, if you want.
      - '5006:5006'
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - data:/data
    restart: unless-stopped
volumes:
  data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=${SHAREIP},rw"
      device: ":${SHAREFOLDER}/actual_data"