services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    secrets:
      - cloudflare_api_token_trigx_trading
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Berlin
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - frontend
    ports:
      - 80:80 # HTTP entryPoints
      - 443:443 # HTTPS entryPoints
      - 8080:8080 # Dashbaord WebGui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - traefik:/certs

volumes:
  traefik:
    name: traefik

networks:
  frontend:
    name: frontend

secrets:
  cloudflare_api_token_trigx_trading:
    external: true
