version: '3'
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:2021.12.16
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - config:/config
      - library:/books
    ports:
      - 8083:8083
    restart: unless-stopped
volumes:
  config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=${SHAREIP},rw"
      device: ":${SHAREFOLDER}/calibre_config"
  library:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=${SHAREIP},rw"
      device: ":${SHAREFOLDER}/calibre_library"