version: "3"
services:
  5etools-docker:
    container_name: nodered
    image: nodered/node-red:3.1.8
    volumes:
      - nodered_data:/data
    ports:
     - 1880:1880/tcp

volumes:
  nodered_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=${SHAREIP},rw"
      device: ":${SHAREFOLDER}/nodered_data"