version: "3"
services:
  5etools-docker:
    container_name: nodered
    image: nodered/node-red:4.0.0-18
    volumes:
      - nodered_data:/data
    ports:
     - 1880:1880/tcp
    environment:
      - NODE_RED_CREDENTIAL_SECRET=${NODE_RED_CREDENTIAL_SECRET}

volumes:
  nodered_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=${SHAREIP},rw"
      device: ":${SHAREFOLDER}/nodered_data"