version: '3'

# service description
services:

  # cloudflare tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared:2024.3.0
    #build:
    #  context: ./src
    #  dockerfile: ./Dockerfile
    container_name: cloudflare-tunnel
    hostname: cloudflare-tunnel
    restart: unless-stopped
    network_mode: "host"
    command: tunnel --config /data/config.yml run ${NAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/hosts:/etc/hosts
      - data:/data
    labels:
      # enbale watchtower updates
      - "com.centurylinklabs.watchtower.enable=true"
volumes:
  data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=${SHAREIP},rw"
      device: ":${SHAREFOLDER}/cloudflared_data"