version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:2.11.1'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - le:/etc/letsencrypt
    environment:
      - UID=1000
      - PID=1000
volumes:
  data:
  le: