---
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:12.327.0
    hostname: foundry.trigx.trading
    volumes:
      - foundry_data:/data
    environment:
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_KEY}
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
volumes:
  foundry_data: